import { VA_HEAD } from './head-profiles'
import { VA_MENTAL } from './mental-health'

export const VA_AREA_CONDITIONS: Record<string, string[]> = {
  head: VA_HEAD,
  mental: VA_MENTAL,
  neck: [
    'Cervical strain / sprain', 'Cervical radiculopathy', 'Cervical disc disease (DDD)',
    'Cervical spinal stenosis', 'Cervical vertebral fracture', 'Whiplash injury',
    'Cervical spondylosis', 'Torticollis', 'Neck muscle spasm', 'Other neck condition',
  ],
  shoulder: [
    'Rotator cuff tear / tendinopathy', 'Shoulder impingement', 'Shoulder instability / dislocation',
    'Labral tear (SLAP)', 'Frozen shoulder (adhesive capsulitis)', 'AC joint separation',
    'Shoulder arthritis', 'Shoulder bursitis', 'Shoulder fracture', 'Other shoulder condition',
  ],
  back: [
    'Lumbar strain / sprain', 'Lumbar disc herniation', 'Lumbar radiculopathy / sciatica',
    'Degenerative disc disease (lumbar)', 'Spinal stenosis (lumbar)', 'Thoracic strain',
    'Scoliosis', 'Compression fracture', 'Sacroiliac joint dysfunction',
    'Ankylosing spondylitis', 'Intervertebral disc syndrome (IVDS)', 'Other back / spine condition',
  ],
  chest: [
    'Asthma', 'COPD / chronic bronchitis', 'Pulmonary embolism',
    'Costochondritis', 'Rib fracture', 'Restrictive lung disease',
    'Sleep apnea', 'Pleural effusion', 'Pneumothorax',
    'Chronic cough', 'Chest wall pain', 'Other chest / lung condition',
  ],
  abdomen: [
    'GERD / acid reflux', 'Irritable bowel syndrome (IBS)', 'Hiatal hernia',
    'Inguinal hernia', 'Peptic ulcer disease', "Crohn's disease",
    'Ulcerative colitis', 'Gallbladder disease', 'Kidney stones',
    'Liver condition', 'Bladder condition', 'Pelvic pain', 'Other abdominal condition',
  ],
  hip: [
    'Hip osteoarthritis', 'Hip labral tear', 'Hip bursitis (trochanteric)',
    'Hip impingement (FAI)', 'Hip fracture', 'Avascular necrosis of hip',
    'Hip flexor strain', 'Snapping hip syndrome', 'Hip replacement (total)',
    'Other hip condition',
  ],
  elbow: [
    'Lateral epicondylitis (tennis elbow)', "Medial epicondylitis (golfer's elbow)",
    'Elbow bursitis (olecranon)', 'Cubital tunnel syndrome', 'Elbow fracture',
    'Elbow arthritis', 'Forearm fracture', 'Forearm muscle strain',
    'Elbow dislocation', 'Other elbow / forearm condition',
  ],
  wrist_hand: [
    'Carpal tunnel syndrome', "De Quervain's tenosynovitis", 'Wrist fracture',
    'Trigger finger', "Dupuytren's contracture", 'Hand / finger fracture',
    'Wrist sprain', 'Ganglion cyst', 'Wrist arthritis', 'Hand arthritis',
    "Raynaud's phenomenon", 'Other wrist / hand condition',
  ],
  knee: [
    'Knee osteoarthritis', 'ACL tear / reconstruction', 'Meniscus tear',
    'Patellar tendinitis', 'Patellofemoral syndrome', 'MCL / LCL sprain',
    'Knee bursitis', 'Knee instability', 'Knee replacement (total)',
    "Baker's cyst", 'Chondromalacia patella', 'Other knee condition',
  ],
  leg: [
    'Shin splints (MTSS)', 'Stress fracture (tibia / fibula)', 'Hamstring strain',
    'Quadriceps strain', 'Calf strain / tear', 'Deep vein thrombosis (DVT)',
    'Peripheral neuropathy', 'Femur fracture', 'Compartment syndrome',
    'Varicose veins', 'Muscle atrophy', 'Other leg condition',
  ],
  ankle_foot: [
    'Ankle sprain (chronic)', 'Ankle instability', 'Achilles tendinitis / rupture',
    'Plantar fasciitis', 'Flat feet (pes planus)', 'Ankle fracture',
    'Foot fracture (metatarsal / stress)', 'Bunion (hallux valgus)', 'Heel spurs',
    "Morton's neuroma", 'Tarsal tunnel syndrome', 'Diabetic foot neuropathy',
    'Other ankle / foot condition',
  ],
  systemic: [
    'Systemic lupus erythematosus (SLE)', 'Rheumatoid arthritis', 'Multiple sclerosis',
    'Myasthenia gravis', 'Guillain-Barré syndrome', "Sjögren's syndrome",
    'Psoriatic arthritis', 'Celiac disease',
    'Diabetes mellitus', 'Diabetes mellitus, Type 2', 'Diabetes mellitus, Type 1',
    'Hypothyroidism', "Hashimoto's thyroiditis", 'Hyperthyroidism', "Graves' disease",
    "Addison's disease", "Cushing's syndrome", 'Hyperparathyroidism',
    'Hypogonadism / low testosterone',
    "Parkinson's disease", 'Seizure disorder (epilepsy)',
    'Restless leg syndrome', 'Peripheral artery disease',
    'Dermatitis or eczema', 'Psoriasis', 'Acne vulgaris', 'Contact dermatitis',
    'Seborrheic dermatitis', 'Pseudofolliculitis barbae', 'Folliculitis',
    'Hidradenitis suppurativa', 'Alopecia areata', 'Chloracne',
    "Tinea pedis (athlete's foot)", 'Hyperhidrosis', 'Chronic urticaria', 'Vitiligo',
    'Skin cancer (basal cell, squamous cell, melanoma)', 'Keloid scarring',
    'Scar(s), unstable or painful', 'Burn scar(s)',
    'Fibromyalgia', 'Chronic fatigue syndrome', 'Chronic pain syndrome',
    'Hypertension', "Raynaud's syndrome", "Raynaud's phenomenon",
    'GERD / acid reflux', 'Hiatal hernia', 'Irritable bowel syndrome (IBS)',
    'Erectile dysfunction', 'Loss of use of creative organ',
    'SIRVA (shoulder injury related to vaccine administration)',
    'Myocarditis (vaccine-related)', 'Transverse myelitis',
    'Small fiber neuropathy', 'CIDP (chronic inflammatory demyelinating polyneuropathy)',
    'Constrictive bronchiolitis', 'Respiratory cancer',
    'Kidney cancer / renal cell carcinoma', 'Bladder cancer', 'Prostate cancer',
    'Pancreatic cancer', 'Glioblastoma / brain cancer',
    'Sickle cell anemia', 'Iron deficiency anemia',
    'Lyme disease', 'Sarcoidosis', 'HIV/AIDS', 'Hepatitis B', 'Hepatitis C',
    'Gout', 'Obesity (secondary)', 'Amyloidosis',
    'Other systemic condition',
  ],
}

export const PHYS_EXAMPLES: Record<string, string> = {
  'Cervical radiculopathy': 'arm numbness, tingling, shooting pain',
  'Cervical spondylosis': 'neck stiffness, grinding, bone spurs',
  'Torticollis': 'neck stuck turned to one side',
  'Labral tear (SLAP)': 'clicking, catching, deep shoulder pain',
  'AC joint separation': 'bump on top of shoulder, pain reaching across body',
  'Shoulder impingement': 'pain raising arm overhead',
  'Lumbar radiculopathy / sciatica': 'leg pain, numbness, shooting down leg',
  'Sacroiliac joint dysfunction': 'lower back/buttock pain, worse sitting',
  'Spinal stenosis (lumbar)': 'leg weakness, pain walking that eases sitting',
  'Intervertebral disc syndrome (IVDS)': 'back pain with leg symptoms, flare-ups',
  'Costochondritis': 'chest wall pain, mimics heart attack',
  'Restrictive lung disease': 'difficulty taking deep breaths',
  'Cubital tunnel syndrome': 'elbow tingling, ring/pinky finger numbness',
  "De Quervain's tenosynovitis": 'thumb/wrist pain, difficulty gripping',
  "Dupuytren's contracture": "fingers curling inward, can't straighten",
  'Ganglion cyst': 'lump on wrist, aching',
  'Trigger finger': 'finger catching/locking when bending',
  'Patellofemoral syndrome': 'knee cap pain, grinding going up stairs',
  'Chondromalacia patella': 'cartilage softening, knee cap grinding',
  "Baker's cyst": 'swelling behind knee, tightness',
  'Shin splints (MTSS)': 'lower leg pain during activity',
  'Compartment syndrome': 'tightness, swelling, pressure in leg',
  'Deep vein thrombosis (DVT)': 'leg swelling, warmth, pain in calf',
  'Tarsal tunnel syndrome': 'foot/ankle tingling, burning',
  "Morton's neuroma": 'ball of foot pain, toe numbness',
  'Flat feet (pes planus)': 'arch pain, tired feet, overpronation',
  'Plantar fasciitis': 'heel pain, worse first steps in morning',
  'Peripheral vestibular disorders': 'dizziness, balance problems',
  "Meniere's syndrome (endolymphatic hydrops)": 'vertigo episodes, ringing, hearing loss',
  'Optic neuropathy': 'vision loss, color fading',
  'Papilledema': 'headaches, blurred vision from pressure',
  'Keratoconus': 'blurry/distorted vision, light sensitivity',
  'Otosclerosis': 'gradual hearing loss, ringing',
  'Pterygium': 'growth on eye surface, irritation',
  'Sinusitis, chronic': 'facial pressure, headaches, nasal drainage, congestion',
  'Rhinitis, allergic or vasomotor': 'chronic congestion, runny nose, sneezing',
  'Temporomandibular disorder (TMD)': 'jaw pain, clicking, difficulty chewing',
  'Residuals of Traumatic Brain Injury (TBI)': 'memory loss, headaches, concentration problems',
  'Seizure disorder (epilepsy)': 'seizures, loss of consciousness, convulsions',
  'Systemic lupus erythematosus (SLE)': 'joint pain, skin rash, fatigue, organ inflammation',
  'Rheumatoid arthritis': 'joint swelling, morning stiffness, fatigue, symmetrical joint pain',
  'Multiple sclerosis': 'numbness, vision problems, fatigue, balance issues',
  'Myasthenia gravis': 'muscle weakness, drooping eyelids, difficulty swallowing',
  'Guillain-Barré syndrome': 'ascending weakness, tingling, paralysis after infection/vaccine',
  "Sjögren's syndrome": 'dry eyes, dry mouth, joint pain, fatigue',
  'Psoriatic arthritis': 'joint pain with skin plaques, swollen fingers/toes',
  'Celiac disease': 'digestive issues, bloating, fatigue from gluten',
  'Diabetes mellitus': 'high blood sugar, frequent urination, thirst, fatigue',
  'Hypothyroidism': 'fatigue, weight gain, cold intolerance, depression',
  "Hashimoto's thyroiditis": 'fatigue, weight gain, cold sensitivity, thyroid swelling',
  'Hyperthyroidism': 'weight loss, rapid heartbeat, tremor, anxiety',
  "Graves' disease": 'bulging eyes, weight loss, rapid heartbeat, tremor',
  "Addison's disease": 'fatigue, weight loss, low blood pressure, darkened skin',
  "Cushing's syndrome": 'weight gain, moon face, thin skin, muscle weakness',
  'Hyperparathyroidism': 'bone pain, kidney stones, fatigue, depression',
  'Hypogonadism / low testosterone': 'fatigue, low libido, mood changes, muscle loss',
  "Parkinson's disease": 'tremor, rigidity, slow movement, balance problems',
  'Restless leg syndrome': 'urge to move legs, worse at rest/night, tingling',
  'Peripheral artery disease': 'leg pain when walking, numbness, cold legs/feet',
  'Dermatitis or eczema': 'itchy, red, inflamed skin patches',
  'Psoriasis': 'thick, scaly skin patches, itching, flaking',
  'Contact dermatitis': 'skin rash from chemical/material exposure',
  'Seborrheic dermatitis': 'flaky, scaly skin on scalp and face',
  'Pseudofolliculitis barbae': 'razor bumps, ingrown hairs, scarring',
  'Folliculitis': 'inflamed hair follicles, bumps, itching',
  'Hidradenitis suppurativa': 'painful lumps under skin, abscesses, scarring',
  'Alopecia areata': 'patchy hair loss, autoimmune',
  'Chloracne': 'acne-like skin lesions from chemical exposure',
  "Tinea pedis (athlete's foot)": 'itchy, cracking skin on feet, fungal infection',
  'Hyperhidrosis': "excessive sweating beyond what's needed for cooling",
  'Skin cancer (basal cell, squamous cell, melanoma)': 'abnormal skin growth, changing moles',
  'Keloid scarring': 'raised, overgrown scar tissue beyond wound area',
  'Fibromyalgia': 'widespread pain, tender points, fatigue, brain fog',
  'Chronic fatigue syndrome': 'debilitating fatigue, post-exertional malaise, brain fog',
  'Chronic pain syndrome': 'persistent pain affecting daily function',
  'Hypertension': 'high blood pressure, headaches, often silent',
  "Raynaud's syndrome": "fingers/toes turn white/blue in cold, numbness",
  "Raynaud's phenomenon": "fingers/toes turn white/blue in cold, numbness",
  'GERD / acid reflux': 'heartburn, regurgitation, difficulty swallowing',
  'Hiatal hernia': 'chest pain, acid reflux, difficulty swallowing',
  'Erectile dysfunction': 'loss of erectile power, may qualify for SMC-K',
  'Loss of use of creative organ': 'loss/removal of testicle, ovary, or penis; SMC-K eligible',
  'SIRVA (shoulder injury related to vaccine administration)': 'shoulder pain/weakness after injection, limited motion',
  'Myocarditis (vaccine-related)': 'chest pain, shortness of breath, fatigue after vaccination',
  'Transverse myelitis': 'back pain, weakness, numbness, bladder/bowel issues',
  'Small fiber neuropathy': 'burning pain, tingling in hands/feet, temperature sensitivity',
  'CIDP (chronic inflammatory demyelinating polyneuropathy)': 'progressive weakness, numbness, impaired walking',
  'Constrictive bronchiolitis': 'shortness of breath, cough from toxic exposure',
  'Gout': 'sudden severe joint pain, swelling, redness (often big toe)',
  'Sarcoidosis': 'swollen lymph nodes, lung involvement, skin lesions, fatigue',
  'Lyme disease': 'joint pain, fatigue, neurological issues from tick bite',
  'Irritable bowel syndrome (IBS)': 'abdominal pain, bloating, diarrhea/constipation',
}

// Maps pin key → secondary condition group key
export const KEY_TO_GROUP: Record<string, string> = {}

;([
  ['head',       ['head', 'leftEar', 'rightEar', 'leftEye', 'rightEye', 'nose', 'jaw']],
  ['neck',       ['neck']],
  ['shoulder',   ['leftShoulder', 'rightShoulder']],
  ['back',       ['upperBack', 'spine', 'lowerBack']],
  ['chest',      ['chest', 'leftLung', 'rightLung']],
  ['abdomen',    ['abdomen', 'pelvis', 'glutes']],
  ['hip',        ['leftHip', 'rightHip']],
  ['elbow',      ['leftElbow', 'rightElbow']],
  ['wrist_hand', ['leftWrist', 'rightWrist', 'leftForearm', 'rightForearm', 'leftHand', 'rightHand']],
  ['knee',       ['leftKnee', 'rightKnee']],
  ['leg',        ['leftThigh', 'rightThigh', 'leftShin', 'rightShin', 'leftHamstring', 'rightHamstring', 'leftCalf', 'rightCalf']],
  ['ankle_foot', ['leftAnkle', 'rightAnkle', 'leftFoot', 'rightFoot']],
  ['mental',     ['mental']],
  ['systemic',   ['systemic']],
] as [string, string[]][]).forEach(([group, keys]) => keys.forEach(k => { KEY_TO_GROUP[k] = group }))

export function getGroupForKey(key: string): string {
  return KEY_TO_GROUP[key] ?? 'other'
}
