import { VA_MENTAL, MENTAL_SECONDARIES } from './mental-health'

export const SECONDARY_MAP: Record<string, string[]> = {
  head: [
    'Migraine headaches', 'TBI residuals', 'TMJ disorder', 'Tinnitus',
    'Vision impairment', 'Cognitive disorder', 'Vertigo / Dizziness',
    ...MENTAL_SECONDARIES,
    'Hearing impairment (hearing loss)',
    'Chronic suppurative otitis media, mastoiditis, or cholesteatoma (or any combination)',
    'Chronic nonsuppurative otitis media with effusion (serious otitis media)',
    'Otosclerosis', 'Peripheral vestibular disorders',
    "Meniere's syndrome (endolymphatic hydrops)", 'Loss of auricle',
    'Malignant neoplasm of the ear (other than skin only)',
    'Benign neoplasms of the ear (other than skin only)',
    'Chronic otitis externa', 'Tympanic membrane, perforation of',
    'Tinnitus, recurrent',
    'Loss of sense of smell, complete', 'Loss of sense of taste, complete',
    'Cataract of any type', 'Aphakia or dislocation of crystalline lens',
    'Diabetic retinopathy', 'Diplopia (double vision)',
    'Disorders of the lacrimal apparatus (epiphora, dacryocystitis, etc.)',
    'Keratoconus', 'Nystagmus, central', 'Optic neuropathy',
    'Retinal dystrophy (including retinitis pigmentosa, wet or dry macular degeneration, early-onset macular degeneration, rod and/or cone dystrophy)',
    'Visual field defects', 'Scotoma, unilateral',
    'Chronic conjunctivitis (nontrachomatous)', 'Pterygium',
    'Ptosis, unilateral or bilateral', 'Papilledema',
    'Post-chiasmal disorders', 'Blepharitis',
    'Temporomandibular disorder (TMD)',
    'Maxilla or mandible, chronic osteomyelitis, osteonecrosis or osteoradionecrosis of',
    'Residuals of Traumatic Brain Injury (TBI)', 'Migraine',
    'Fifth (trigeminal) cranial nerve, Neuralgia',
    'Seventh (facial) cranial nerve, Paralysis of',
    'Brain, vessels, hemorrhage from', 'Brain, vessels, thrombosis of',
    "Burn scar(s) of the head, face, or neck; scar(s) of the head, face, or neck due to other causes; or other disfigurement of the head, face, or neck",
    ...VA_MENTAL,
  ],
  neck: [
    'Cervical radiculopathy', 'Degenerative disc disease (cervical)',
    'Limited ROM - cervical spine', 'Upper extremity numbness / tingling',
    'Migraine headaches', 'IVDS - cervical',
    ...MENTAL_SECONDARIES,
    'The Spine - Lumbosacral or cervical strain',
    'The Spine - Intervertebral disc syndrome',
    'The Spine - Degenerative arthritis, degenerative disc disease other than intervertebral disc syndrome (also, see either DC 5003 or 5010)',
    'The Spine - Spinal stenosis', 'The Spine - Spinal fusion',
    'The Spine - Ankylosing spondylitis',
    'The Spine - Spondylolisthesis or segmental instability',
    'The Spine - Vertebral fracture or dislocation',
    'Upper radicular group (fifth and sixth cervicals), Neuralgia',
    'Upper radicular group (fifth and sixth cervicals), Neuritis',
    'Upper radicular group (fifth and sixth cervicals), Paralysis of',
    'Middle radicular group, Neuralgia', 'Middle radicular group, Neuritis',
    'Middle radicular group, Paralysis of',
    'All radicular groups, Paralysis of',
    'The Torso & Neck Group XIX', 'The Torso & Neck Group XX',
    'The Torso & Neck Group XXI', 'The Torso & Neck Group XXII',
    'The Torso & Neck Group XXIII',
    ...VA_MENTAL,
  ],
  shoulder: [
    'Rotator cuff tendinopathy', 'Frozen shoulder (adhesive capsulitis)',
    'Limited ROM - shoulder', 'Thoracic outlet syndrome',
    'Shoulder instability', 'Nerve damage (upper extremity)',
    ...MENTAL_SECONDARIES,
    'The Shoulder & Arm - Arm, limitation of motion of',
    'The Shoulder & Arm - Scapulohumeral articulation, ankylosis of',
    'The Shoulder & Arm - Humerus, other impairment of',
    'The Shoulder & Arm - Clavicle or scapula, impairment of',
    'Shoulder replacement (prosthesis)', 'Rotator cuff tear',
    'Fracture, clavicle', 'Bursitis',
    'Circumflex nerve, Neuralgia', 'Circumflex nerve, Neuritis',
    'Circumflex nerve, Paralysis of',
    'Long thoracic nerve, Neuralgia', 'Long thoracic nerve, Neuritis',
    'Long thoracic nerve, Paralysis of',
    'The Shoulder Girdle & Arm Group I', 'The Shoulder Girdle & Arm Group II',
    'The Shoulder Girdle & Arm Group III', 'The Shoulder Girdle & Arm Group IV',
    'The Shoulder Girdle & Arm Group V', 'The Shoulder Girdle & Arm Group VI',
    ...VA_MENTAL,
  ],
  back: [
    'Lumbar radiculopathy', 'Sciatica',
    'Degenerative disc disease (lumbar)', 'Limited ROM - thoracolumbar spine',
    'IVDS - lumbar', 'Lower extremity numbness / tingling',
    'Erectile dysfunction', 'Bladder dysfunction', 'Bowel dysfunction',
    'Abnormal gait',
    ...MENTAL_SECONDARIES,
    'The Spine - Lumbosacral or cervical strain',
    'The Spine - Intervertebral disc syndrome',
    'The Spine - Degenerative arthritis, degenerative disc disease other than intervertebral disc syndrome (also, see either DC 5003 or 5010)',
    'The Spine - Sacroiliac injury and weakness',
    'The Spine - Spinal stenosis', 'The Spine - Spinal fusion',
    'The Spine - Ankylosing spondylitis',
    'The Spine - Spondylolisthesis or segmental instability',
    'The Spine - Vertebral fracture or dislocation',
    'Scoliosis, dorsal', 'Kyphosis, dorsal',
    'Lower radicular group, Neuralgia', 'Lower radicular group, Neuritis',
    'Lower radicular group, Paralysis of',
    'All radicular groups, Paralysis of',
    'Sciatic nerve, Neuralgia', 'Sciatic nerve, Neuritis', 'Sciatic nerve, Paralysis of',
    'Spinal cord, new growths of: benign, minimum rating',
    'Syringomyelia', 'Myelitis',
    'Impotency', 'Cystitis, chronic, includes interstitial and all etiologies, infectious and non-infectious',
    ...VA_MENTAL,
  ],
  chest: [
    'Costochondritis', 'Respiratory condition', 'GERD', 'Scarring',
    'Anxiety / Panic disorder',
    ...MENTAL_SECONDARIES,
    'Valvular heart disease (including rheumatic heart disease)',
    'Arteriosclerotic heart disease (Coronary artery disease)',
    'Hypertensive heart disease',
    'Hypertensive vascular disease (hypertension and isolated systolic hypertension)',
    'Myocardial infarction', 'Cardiomyopathy', 'Pericarditis',
    'Supraventricular arrhythmias', 'Ventricular arrhythmias (sustained)',
    'Atrioventricular block', 'Endocarditis',
    'Coronary bypass surgery', 'Heart valve replacement (prosthesis)',
    'Varicose veins', "Raynaud's syndrome",
    'Asthma, bronchial', 'Chronic obstructive pulmonary disease',
    'Bronchitis, chronic', 'Bronchiectasis', 'Emphysema, pulmonary',
    'Sleep apnea syndromes (Obstructive, central, mixed)',
    'Reactive airway disease', 'Sarcoidosis',
    'Chronic pleural effusion or fibrosis',
    'Diffuse interstitial fibrosis (interstitial pneumonitis, fibrosing alveolitis)',
    'Pulmonary embolus', 'Pulmonary vascular disease',
    'Traumatic chest wall defect, pneumothorax, hernia, etc.',
    'Post-surgical residual (lobectomy, pneumonectomy, etc.)',
    'Kyphoscoliosis, pectus excavatum, pectus carinatum',
    'Fracture, ribs', 'Ribs, removal of',
    ...VA_MENTAL,
  ],
  abdomen: [
    'GERD', 'IBS', 'Hernia', 'Bladder dysfunction',
    'Erectile dysfunction', 'Pelvic pain syndrome',
    ...MENTAL_SECONDARIES,
    'Gastroesophageal reflux disease', 'Gastritis, chronic', 'Peptic ulcer disease',
    'Irritable bowel syndrome', 'Colitis, ulcerative',
    "Crohn's disease or undifferentiated form of inflammatory bowel disease",
    'Diverticulitis and diverticulosis', 'Enteritis, chronic',
    'Hiatal hernia and paraesophageal hernia',
    'Hernia, including femoral, inguinal, umbilical, ventral, incisional, and other (but not including hiatal)',
    'Pancreatitis, chronic', 'Cirrhosis of the liver',
    'Chronic liver disease without cirrhosis', 'Hepatitis C (or non-A, non-B hepatitis)',
    'Cholelithiasis, chronic',
    'Cholecystectomy (gallbladder removal), complications of (such as strictures and biliary leaks)',
    'Postgastrectomy syndromes', 'Visceroptosis, symptomatic, marked',
    'Rectum and anus, impairment of sphincter control',
    'Hemorroids, external or internal',
    'Peritoneum, adhesions of, due to surgery, trauma, or infection',
    'Chronic renal disease requiring regular dialysis', 'Kidney transplant',
    'Kidney, removal of one', 'Nephritis, chronic', 'Nephrolithiasis',
    'Prostate gland injuries, infections, hypertrophy, post-operative residuals',
    'Cystitis, chronic, includes interstitial and all etiologies, infectious and non-infectious',
    'Bladder, injury of', 'Impotency',
    'Endometriosis',
    'Complete or incomplete pelvic organ prolapse due to injury, disease, or surgical complications of pregnancy',
    'Uterus, removal of, including corpus', 'Ovary, removal of',
    'Diabetes mellitus', 'Hypothyroidism',
    "Hyperthyroidism, including, but not limited to, Graves' disease",
    "Addison's disease (adrenocortical insufficiency)", "Cushing's syndrome",
    ...VA_MENTAL,
  ],
  hip: [
    'Limited ROM - hip', 'Hip labral tear', 'Abnormal gait',
    'Leg length discrepancy', 'Sciatic nerve involvement',
    'Degenerative joint disease - hip',
    ...MENTAL_SECONDARIES,
    'The Hip and Thigh - Hip, ankylosis of',
    'The Hip and Thigh - Hip, flail joint',
    'The Hip and Thigh - Thigh, limitation of flexion of',
    'The Hip and Thigh - Thigh, limitation of extension of',
    'The Hip and Thigh - Thigh, impairment of',
    'The Hip and Thigh - Femur, impairment of',
    'Hip replacement (prosthesis)',
    'Degenerative arthritis, other than post-traumatic',
    'Post-traumatic arthritis', 'Bursitis',
    'Sciatic nerve, Neuralgia', 'Sciatic nerve, Neuritis', 'Sciatic nerve, Paralysis of',
    'External cutaneous nerve of thigh, Neuralgia',
    'External cutaneous nerve of thigh, Neuritis',
    'External cutaneous nerve of thigh, Paralysis of',
    'Obturator nerve, Neuralgia', 'Obturator nerve, Neuritis',
    'Obturator nerve, Paralysis of',
    'The Pelvic Girdle & Thigh Rating Group XIII',
    'The Pelvic Girdle & Thigh Rating Group XIV',
    'The Pelvic Girdle & Thigh Rating Group XV',
    'The Pelvic Girdle & Thigh Rating Group XVI',
    'The Pelvic Girdle & Thigh Rating Group XVII',
    'The Pelvic Girdle & Thigh Rating Group XVIII',
    ...VA_MENTAL,
  ],
  elbow: [
    'Cubital tunnel syndrome', 'Tennis elbow (lateral epicondylitis)',
    "Golfer's elbow (medial epicondylitis)", 'Limited ROM - elbow',
    'Nerve damage (upper extremity)',
    ...MENTAL_SECONDARIES,
    'The Elbow & Forearm - Elbow, ankylosis of',
    'The Elbow & Forearm - Elbow, other impairment of flail joint',
    'The Elbow & Forearm - Forearm, limitation of flexion of',
    'The Elbow & Forearm - Forearm, limitation of extension of',
    'The Elbow & Forearm - Forearm, flexion limited to 100 degrees and extension to 45 degrees',
    'The Elbow & Forearm - Supination and pronation, impairment of',
    'The Elbow & Forearm - Radius, impairment of',
    'The Elbow & Forearm - Ulna, impairment of',
    'The Elbow & Forearm - Radius and ulna, nonunion of, with flail false joint',
    'Elbow replacement (prosthesis)',
    'Epicondylitis (lateral or medial)', 'Bursitis',
    'Musculocutaneous nerve, Neuralgia', 'Musculocutaneous nerve, Neuritis',
    'Musculocutaneous nerve, Paralysis of',
    'The musculospiral nerve (radial nerve), Neuralgia',
    'The musculospiral nerve (radial nerve), Neuritis',
    'The musculospiral nerve (radial nerve), Paralysis of',
    ...VA_MENTAL,
  ],
  wrist_hand: [
    'Carpal tunnel syndrome', "De Quervain's tenosynovitis",
    'Trigger finger', 'Limited ROM - wrist',
    'Peripheral neuropathy (upper)', 'Grip strength loss',
    ...MENTAL_SECONDARIES,
    'The Wrist - Wrist, ankylosis of', 'The Wrist - Wrist, limitation of motion of',
    'Wrist replacement (prosthesis)', 'Fracture, wrist',
    "Dupuytren's contracture", 'Ganglia (ganglion cysts)',
    'Thumb, limitation of motion',
    'Index or long finger, limitation of motion',
    'Ring or little finger, limitation of motion',
    'Tenosynovitis, tendinitis, tendinosis or tendinopathy',
    'The median nerve, Neuralgia', 'The median nerve, Neuritis',
    'The median nerve, Paralysis of',
    'The ulnar nerve, Neuralgia', 'The ulnar nerve, Neuritis',
    'The ulnar nerve, Paralysis of',
    'The Forearm & Hand Group VII', 'The Forearm & Hand Group VIII',
    'The Forearm & Hand Group IX',
    ...VA_MENTAL,
  ],
  knee: [
    'Limited ROM - knee', 'Degenerative joint disease - knee',
    'Meniscal tear', 'Patellar tendinitis', "Baker's cyst",
    'Instability / Giving way', 'Abnormal gait',
    ...MENTAL_SECONDARIES,
    'The Knee & Leg - Knee, ankylosis of',
    'The Knee & Leg - Knee, other impairment of',
    'The Knee & Leg - Leg, limitation of flexion of',
    'The Knee & Leg - Leg, limitation of extension of',
    'The Knee & Leg - Cartilage, semilunar, dislocated, with frequent episodes of locking, pain, and effusion into the joint',
    'The Knee & Leg - Cartilage, semilunar, removal of, symptomatic',
    'The Knee & Leg - Tibia and fibula, impairment of',
    'The Knee & Leg - Genu recurvatum (acquired, traumatic, with weakness and insecurity in weight-bearing objectively demonstrated)',
    'Knee replacement (prosthesis)', 'Chondromalacia patella',
    'Patellofemoral syndrome/retropatellar', 'Patellectomy',
    'Fracture, knee', 'Hypotonia, ligaments, knees',
    'Degenerative arthritis, other than post-traumatic', 'Post-traumatic arthritis',
    'Bursitis', "Disease, Osgood-Schlatter's", 'Disease, Pellegrini-Stieda',
    'Varus deformity, knee (genu varum/bowlegs)',
    'External popliteal nerve (common peroneal), Neuralgia',
    'External popliteal nerve (common peroneal), Neuritis',
    'External popliteal nerve (common peroneal), Paralysis of',
    'Internal popliteal nerve (tibial), Neuralgia',
    'Internal popliteal nerve (tibial), Neuritis',
    'Internal popliteal nerve (tibial), Paralysis of',
    ...VA_MENTAL,
  ],
  leg: [
    'Peripheral neuropathy (lower)', 'Shin splints (MTSS)',
    'Muscle atrophy', 'Deep vein thrombosis residuals',
    'Compartment syndrome', 'Abnormal gait',
    ...MENTAL_SECONDARIES,
    'The Knee & Leg - Tibia and fibula, impairment of',
    'Bones, of the lower extremity, shortening of',
    'Degenerative arthritis, other than post-traumatic', 'Post-traumatic arthritis',
    'Osteomyelitis, acute, subacute, or chronic',
    'Anterior crural femoral, Neuralgia', 'Anterior crural femoral, Neuritis',
    'Anterior crural femoral, Paralysis of',
    'Anterior tibial nerve (deep peroneal), Neuralgia',
    'Anterior tibial nerve (deep peroneal), Neuritis',
    'Anterior tibial nerve (deep peroneal), Paralysis of',
    'Musculocutaneous nerve (superficial peroneal), Neuralgia',
    'Musculocutaneous nerve (superficial peroneal), Neuritis',
    'Musculocutaneous nerve (superficial peroneal), Paralysis of',
    'Internal saphenous nerve, Neuralgia', 'Internal saphenous nerve, Neuritis',
    'Internal saphenous nerve, Paralysis of',
    'The Foot & Leg Group X', 'The Foot & Leg Group XI', 'The Foot & Leg Group XII',
    'Varicose veins', 'Post-phlebitis syndrome of any etiology',
    ...VA_MENTAL,
  ],
  ankle_foot: [
    'Plantar fasciitis', 'Limited ROM - ankle',
    'Flatfoot (pes planus)', 'Ankle instability',
    'Peripheral neuropathy (lower)', 'Abnormal gait',
    'Degenerative joint disease - ankle',
    ...MENTAL_SECONDARIES,
    'The Ankle - Ankle, limited motion of', 'The Ankle - Ankle, ankylosis of',
    'The Ankle - Subastragalar or tarsal joint, ankylosis of',
    'The Ankle - Os calcis or astragalus, malunion of',
    'The Ankle - Astragalectomy',
    'Ankle replacement (prosthesis)',
    'The Foot - Flatfoot, acquired', 'The Foot - Claw foot (pes cavus), acquired',
    'The Foot - Hallux valgus, unilateral', 'The Foot - Hallux rigidus, unilateral, severe',
    'The Foot - Hammer toe', 'The Foot - Plantar Fasciitis',
    'The Foot - Metatarsalgia, anterior (Morton\'s disease), unilateral, or bilateral',
    'The Foot - Foot injuries, other', 'The Foot - Weak foot, bilateral',
    'The Foot - Tarsal, or metatarsal bones, malunion of, or nonunion of',
    'Fusion, toes',
    'Degenerative arthritis, other than post-traumatic', 'Post-traumatic arthritis',
    'Gout', 'Bursitis',
    'Posterior tibial nerve, Neuralgia', 'Posterior tibial nerve, Neuritis',
    'Posterior tibial nerve, Paralysis of',
    'Anterior tibial nerve (deep peroneal), Neuralgia',
    'Anterior tibial nerve (deep peroneal), Paralysis of',
    ...VA_MENTAL,
  ],
  mental: [
    ...VA_MENTAL,
    ...MENTAL_SECONDARIES,
    'Medication side effects', 'Cognitive disorder',
    'Substance use disorder',
  ],
  systemic: [
    'Systemic lupus erythematosus (SLE)', 'Rheumatoid arthritis', 'Multiple sclerosis',
    'Myasthenia gravis', 'Guillain-Barré syndrome', "Sjögren's syndrome",
    'Psoriatic arthritis', 'Celiac disease',
    'Diabetes mellitus', 'Hypothyroidism', 'Hyperthyroidism', "Graves' disease",
    "Addison's disease", "Cushing's syndrome", 'Hyperparathyroidism',
    'Dermatitis or eczema', 'Psoriasis', 'Acne vulgaris',
    "Scar(s), unstable or painful", 'Chronic urticaria', 'Vitiligo',
    'Fibromyalgia', 'Chronic fatigue syndrome', 'Chronic pain syndrome',
    'Hypertension', "Raynaud's syndrome", 'Seizure disorder (epilepsy)',
    "Parkinson's disease", 'Multiple sclerosis', 'Sickle cell anemia',
    'Lyme disease', 'Sarcoidosis', 'HIV/AIDS', 'Hepatitis B', 'Hepatitis C',
    'Gout', 'Obesity (secondary)',
    ...MENTAL_SECONDARIES,
    ...VA_MENTAL,
  ],
  other: [
    ...MENTAL_SECONDARIES,
    'Medication side effects', 'Chronic fatigue',
    'Sickle cell anemia', 'Iron deficiency anemia', 'Aplastic anemia',
    'Immune thrombocytopenia', "Hodgkin's lymphoma", "Non-Hodgkin's lymphoma",
    'Multiple myeloma', 'Polycythemia vera',
    'Lyme disease', 'Rheumatic fever', 'Sarcoidosis', 'Tuberculosis, miliary',
    'Dermatitis or eczema', 'Psoriasis', 'Acne vulgaris',
    "Scar(s), unstable or painful", 'Chronic urticaria', 'Vitiligo',
    'Diabetes mellitus', 'Hypothyroidism',
    ...VA_MENTAL,
  ],
}

export function getSecondariesForGroup(group: string): string[] {
  return SECONDARY_MAP[group] ?? SECONDARY_MAP.other
}
